<a href="https://colab.research.google.com/github/ThangDoan2001/TensorFlow_ZeroToHero/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensers
* Getting information from tensors
* Manipulating tensors
* Tensos & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* using GPUs with TensorFlow (or TPUs)
* Exercises to try for your self

## Introduction to Tensors

In [138]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__)

2.5.0


In [139]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [140]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [141]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [142]:
# Check the dimension of our vector
vector.ndim

1

In [143]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [144]:
matrix.ndim

2

In [145]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype paramet 
another_matrix   

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [146]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [147]:
# Let's create a tensor 
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [148]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2 dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar. a 1-dimensional tensor is a array)


### Creating tensors with tf.Variable()


In [149]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [150]:
# Let's try change one of the elements in out changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change one of the elements in our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

**Note** : Rearly in practice will you need to decide whethert to use tf.constant of tf.Variable to create tensorsm, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
# Create two random(but the same) tensors
random_1 = tf.random.Generator.from_seed(24) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(24)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn;t affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle out non-shuffled tensor
tf.random.set_seed(42) # Global level seed
shuffled = tf.random.shuffle(not_shuffled, seed=42) # Operation-level seed 


In [ ]:
# Using global seed to shuffle a tensor
tf.random.set_seed(59)
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

In [ ]:
# Using operation-level seed to shuffle a tensor\
shuffled_tensor = tf.random.shuffle(not_shuffled, seed=59)
shuffled_tensor
# It doesn't make sense

In [ ]:
# Try to create tensor in many ways 
tensor_1 = tf.constant([5, 9, 21])     #Unchangeable tensor
tensor_2 = tf.Variable([[5, 9],        #Changeable tensor(e.g. tensor_2[0].assign(9))
                            [23, 10]])
tensor_3 = tf.random.Generator.from_seed(59).normal(shape=(3, 2))
tensor_1, tensor_2, tensor_3


In [ ]:
# Practice shuffle 
# We have two ways to shuffle a tensor including using global-level seed or using operation-level seed
# Global-level seed so the shuffle version is immutable through many operation times.
tf.random.set_seed(59)
tensor_4 = tf.random.shuffle(tensor_3)
# Using operation-level seed, the shuffle version will be changed every time we run the code
tensor_5 = tf.random.shuffle(tensor_3, seed=55) # No need seed as a parameter
tensor_4, tensor_5
# You may see tensor_5 isn't changed every we run because we set_seed before it

It looks like if we want our shuffled tensor to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

**Rule 4 : "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence"**

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

### Turn Numpy arrays into tensors 

The main difference between Numpy array and Tensorflow tensors is that tensors acan be run on a GPU(much faster for numerical computing)

In [ ]:
# You can also turn Numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NUmpy array beteween 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector)   # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

In [ ]:
A.ndim

### Getting informaition from tensors

When dealing with tensors you probably want to be aware to the following attributes
* Shape                 : tensor.shape
* Rank                  : tensor.ndim
* Axis or dimension     : tensor[0], tensor[:, 1]
* Size                  : tf.size(tensor)

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of out tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number pf dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axies: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy()) # Just need to add .numpy()


### Indexing tensors

Tensors can be indexed just like Python lists.


In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1, :1, :1]
rank_4_tensor[:1, :1, :1, :]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Add in extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
# rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #"-1" means expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1 )

### Manipulating tensors ( tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`



In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor 

In [ ]:
# Muptiplication also works
tensor * 10

In [ ]:
# Subtraction if you want
tensor - 10

In [ ]:
# We can use the tensorflow built-in functino too
tf.multiply(tensor, 10)

In [ ]:
tf.multiply(tensor, tensor)

In [ ]:
tf.add(tensor, 10)
tf.subtract(tensor, 10)
tf.multiply(tensor, 10)
tf.divide(tensor, 10)

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operation

There are two rules our tensor (or matrices) need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensorFlow
print(tensor)
tf.linalg.matmul(tensor, tensor)

In [ ]:
# Matrix mutliplication with Python operator "@"
tensor @ tensor

In [ ]:
# Create a tensor (3, 2)

X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

X, Y

In [ ]:
#Try to matrix multiply tensors of same shape
Y @ Y

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))


In [ ]:
X.shape ,tf.reshape(Y, shape=(2, 3)).shape

In [ ]:
# Try to multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.linalg.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.linalg.matmul(tf.reshape(X, shape=(2, 3)), Y)

In [ ]:
# Can do the same with transpose
tf.transpose(X) 
# The result of tf.transpose is different than that of tf.reshape

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

**The dot product** 

Matrix multiplication is also refferred to as the dot product.

You can perform matrix multiplication using:

*`tf.matmul()`

*`tf.tensordot()`

*`@`

In [ ]:
# Perform the dot product on X and Y requires X or Y to be transposed
tf.tensordot(tf.transpose(X), Y, axes=1)


In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))


In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.linalg.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y :")
print(Y, "\n")

print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, shape=(2, 3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

In [ ]:
tf.linalg.matmul(X, tf.transpose(Y))

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default dataype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

In [151]:
# Change from float 32 to float 16 (reduce percision)
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [153]:
# Change from 32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [156]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16.dtype

tf.float16

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [158]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [159]:
# Get the absolute values (make all element be positive)
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the minimum

* Get the maximum

* Get the mean of a tensor

* get the sum of a tensor



In [161]:
# Create a random tensor withs values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([11, 68,  8, 91, 19, 91, 50, 99, 34, 12, 74, 94, 68, 91, 55, 31, 16,
       69, 47, 98, 69, 44, 37, 36, 38, 71, 86,  2, 19,  3, 39, 28, 60, 23,
       20, 49, 56, 22, 55, 52, 54, 59, 35,  4,  3, 49, 28, 87,  9, 57])>

In [163]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [165]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [167]:
np.min(E)

2

In [169]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [171]:
np.max(E)

99

In [173]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [175]:
np.mean(E)

46.4

In [177]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2320>

In [179]:
np.sum(E)

2320

**Exercise :** With what we've just learn, find the variance and standard deviation of our `E` tensor using TensorFlow methods.

In [185]:
# To find the variance of our tensor, we need access to tensorflow_probability

import tensorflow_probability as tfp
tfp.stats.variance(E)



<tf.Tensor: shape=(), dtype=int64, numpy=793>

In [187]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.160255>

In [ ]:
tf.math.reduce_std(E)