<a href="https://colab.research.google.com/github/ThangDoan2001/TensorFlow_ZeroToHero/blob/master/00_tensorflow_fundamentals_p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensers
* Getting information from tensors
* Manipulating tensors
* Tensos & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* using GPUs with TensorFlow (or TPUs)
* Exercises to try for your self

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__)

2.5.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype paramet 
another_matrix   

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor 
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2 dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar. a 1-dimensional tensor is a array)


### Creating tensors with tf.Variable()


In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in out changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change one of the elements in our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

**Note** : Rearly in practice will you need to decide whethert to use tf.constant of tf.Variable to create tensorsm, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
# Create two random(but the same) tensors
random_1 = tf.random.Generator.from_seed(24) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(24)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn;t affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle out non-shuffled tensor
tf.random.set_seed(42) # Global level seed
shuffled = tf.random.shuffle(not_shuffled, seed=42) # Operation-level seed 


In [ ]:
# Using global seed to shuffle a tensor
tf.random.set_seed(59)
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
# Using operation-level seed to shuffle a tensor\
shuffled_tensor = tf.random.shuffle(not_shuffled, seed=59)
shuffled_tensor
# It doesn't make sense

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Try to create tensor in many ways 
tensor_1 = tf.constant([5, 9, 21])     #Unchangeable tensor
tensor_2 = tf.Variable([[5, 9],        #Changeable tensor(e.g. tensor_2[0].assign(9))
                            [23, 10]])
tensor_3 = tf.random.Generator.from_seed(59).normal(shape=(3, 2))
tensor_1, tensor_2, tensor_3


(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5,  9, 21], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[ 5,  9],
        [23, 10]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.9465717 , -0.7108357 ],
        [ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866]], dtype=float32)>)

In [ ]:
# Practice shuffle 
# We have two ways to shuffle a tensor including using global-level seed or using operation-level seed
# Global-level seed so the shuffle version is immutable through many operation times.
tf.random.set_seed(59)
tensor_4 = tf.random.shuffle(tensor_3)
# Using operation-level seed, the shuffle version will be changed every time we run the code
tensor_5 = tf.random.shuffle(tensor_3, seed=55) # No need seed as a parameter
tensor_4, tensor_5
# You may see tensor_5 isn't changed every we run because we set_seed before it

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866],
        [-0.9465717 , -0.7108357 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.4713507 , -0.10086866],
        [ 1.2995545 , -0.6149066 ],
        [-0.9465717 , -0.7108357 ]], dtype=float32)>)