<a href="https://colab.research.google.com/github/ThangDoan2001/TensorFlow_ZeroToHero/blob/master/00_tensorflow_fundamentals_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###00 TensorFlow Fundamentals Exercises




In [3]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.5.0'

**1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`**



In [10]:
# Create a vector
A = tf.constant(np.array([3., 7., 10.]))
A.shape[0]

3

In [13]:
# Create a scalar
B = tf.constant(3.)
B

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [15]:
# Create a matrix
C = tf.constant([[5., 9.],
                 [2., 0.],
                 [0., 1.]])
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[5., 9.],
       [2., 0.],
       [0., 1.]], dtype=float32)>

In [16]:
# Create a tensor
D = tf.constant([[[1., 2.],
                  [3., 4.]],
                 [[5., 6.],
                  [7., 8.]]])
D

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]], dtype=float32)>

**2. Find the shape, rank and size of the tensors you created in 1**


In [17]:
print("Datatype of every elements: ", D.dtype, "\n")
print("Number of dimensions(rank): ", D.ndim, "\n")
print("Shape of tensor: ", D.shape, "\n")
print("Element along the 0 axies: ", D.shape[0], "\n" )
print("Element along the last axies: ", D.shape[-1], "\n")
print("Total number in our tensor:  ", tf.size(D).numpy())

Datatype of every elements:  <dtype: 'float32'> 

Number of dimensions(rank):  3 

Shape of tensor:  (2, 2, 2) 

Element along the 0 axies:  2 

Element along the last axies:  2 

Total number in our tensor:   8


**3. Create two tensors containing random values between 0 and 1 with shape [5, 300]**

In [19]:
# Create the first tensor
tf.random.set_seed(42)
E = tf.random.uniform(shape=[5, 300])
E

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [22]:
# Create the second tensor
F = tf.random.uniform(shape=[5, 300], seed=42)
F

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4163028 , 0.26858163, 0.47968316, ..., 0.9737669 , 0.9777365 ,
        0.21718514],
       [0.9787899 , 0.9768691 , 0.6782458 , ..., 0.8427533 , 0.8693787 ,
        0.6705674 ],
       [0.6826352 , 0.06621385, 0.58875644, ..., 0.7543584 , 0.38940334,
        0.7927996 ],
       [0.11849666, 0.60407066, 0.34777546, ..., 0.605     , 0.9107114 ,
        0.50104   ],
       [0.72606504, 0.7984501 , 0.9777988 , ..., 0.5601653 , 0.27684855,
        0.19102657]], dtype=float32)>

**4. Multiply the two tensors you created in 3 using matrix multiplication**

In [28]:
G = tf.linalg.matmul(E, tf.reshape(F, shape=[300, 5]))
G, tf.reshape(F, shape=[300, 5])

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[75.950645, 78.00313 , 75.739494, 75.847305, 79.086334],
        [71.224785, 72.25984 , 71.64622 , 70.63252 , 72.294815],
        [74.35827 , 74.38488 , 76.513855, 73.80008 , 76.498856],
        [71.55604 , 70.64171 , 73.69728 , 71.02696 , 72.954056],
        [75.48393 , 77.92657 , 80.14741 , 79.62825 , 78.7825  ]],
       dtype=float32)>, <tf.Tensor: shape=(300, 5), dtype=float32, numpy=
 array([[0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144],
        [0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096],
        [0.07745171, 0.57921314, 0.29180396, 0.26718032, 0.37012458],
        ...,
        [0.06137466, 0.19803405, 0.72011876, 0.72451043, 0.30379128],
        [0.9961995 , 0.47245634, 0.9308089 , 0.07201004, 0.28703678],
        [0.88451684, 0.7498721 , 0.5601653 , 0.27684855, 0.19102657]],
       dtype=float32)>)

In [31]:
H = tf.linalg.matmul(E, tf.transpose(F))
H, tf.transpose(F)

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.07086 , 73.73577 , 73.45208 , 74.44637 , 79.16407 ],
        [73.122086, 70.910255, 71.50602 , 70.87376 , 75.55717 ],
        [77.15072 , 74.87322 , 73.25278 , 69.333534, 78.06892 ],
        [72.117165, 68.65578 , 73.21626 , 66.979485, 77.03185 ],
        [79.79337 , 77.74287 , 78.53918 , 72.812325, 80.97921 ]],
       dtype=float32)>, <tf.Tensor: shape=(300, 5), dtype=float32, numpy=
 array([[0.4163028 , 0.9787899 , 0.6826352 , 0.11849666, 0.72606504],
        [0.26858163, 0.9768691 , 0.06621385, 0.60407066, 0.7984501 ],
        [0.47968316, 0.6782458 , 0.58875644, 0.34777546, 0.9777988 ],
        ...,
        [0.9737669 , 0.8427533 , 0.7543584 , 0.605     , 0.5601653 ],
        [0.9777365 , 0.8693787 , 0.38940334, 0.9107114 , 0.27684855],
        [0.21718514, 0.6705674 , 0.7927996 , 0.50104   , 0.19102657]],
       dtype=float32)>)

**5. Multiply the two tensors you created in 3 using dot product**

In [34]:
I = tf.tensordot(E, tf.reshape(F, shape=(300, 5)), axes=1)
I

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.950645, 78.00313 , 75.739494, 75.847305, 79.086334],
       [71.224785, 72.25984 , 71.64622 , 70.63252 , 72.294815],
       [74.35827 , 74.38488 , 76.513855, 73.80008 , 76.498856],
       [71.55604 , 70.64171 , 73.69728 , 71.02696 , 72.954056],
       [75.48393 , 77.92657 , 80.14741 , 79.62825 , 78.7825  ]],
      dtype=float32)>

In [41]:
K = tf.tensordot(E, tf.transpose(F), axes=1)
K

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.07086 , 73.73577 , 73.45208 , 74.44637 , 79.16407 ],
       [73.122086, 70.910255, 71.50602 , 70.87376 , 75.55717 ],
       [77.15072 , 74.87322 , 73.25278 , 69.333534, 78.06892 ],
       [72.117165, 68.65578 , 73.21626 , 66.979485, 77.03185 ],
       [79.79337 , 77.74287 , 78.53918 , 72.812325, 80.97921 ]],
      dtype=float32)>

**6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]**

In [43]:
# Create a tensor
tf.random.set_seed(59)
L = tf.random.uniform(shape=(224, 224, 3))
L

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.52018476, 0.28629863, 0.69607365],
        [0.62657845, 0.70456564, 0.13875115],
        [0.43297482, 0.9627955 , 0.32349825],
        ...,
        [0.0944488 , 0.5527396 , 0.35615683],
        [0.5394956 , 0.3232304 , 0.09614515],
        [0.91999125, 0.22759855, 0.6992248 ]],

       [[0.99684286, 0.6041    , 0.03022408],
        [0.10558164, 0.6073203 , 0.9449835 ],
        [0.71624064, 0.95800865, 0.31947064],
        ...,
        [0.14596474, 0.6564189 , 0.75227416],
        [0.98159003, 0.31683004, 0.29083395],
        [0.27285075, 0.7800894 , 0.22806537]],

       [[0.4700148 , 0.9055362 , 0.527663  ],
        [0.37833154, 0.4580952 , 0.3765837 ],
        [0.8995203 , 0.25422537, 0.9057543 ],
        ...,
        [0.5668957 , 0.72967577, 0.8984972 ],
        [0.93596673, 0.06877935, 0.54482543],
        [0.31067312, 0.21359503, 0.24043489]],

       ...,

       [[0.8126823 , 0.4675846 , 0.00461376],
        [0.89

**7. Find the min and max values of the tensor you created in 6 along the first axis**


In [63]:
Q = tf.reduce_max(L, axis=0)
Q

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99684286, 0.9905211 , 0.99638546],
       [0.99579835, 0.9978516 , 0.9994434 ],
       [0.9963902 , 0.9981122 , 0.99808943],
       [0.9984708 , 0.9968709 , 0.9961809 ],
       [0.99988985, 0.999323  , 0.99927783],
       [0.99667966, 0.9995291 , 0.99916065],
       [0.9999603 , 0.9978683 , 0.9966513 ],
       [0.9948318 , 0.99738264, 0.99878454],
       [0.9997163 , 0.99628854, 0.9948758 ],
       [0.9956783 , 0.9972625 , 0.99698234],
       [0.99421775, 0.9978986 , 0.9910282 ],
       [0.9796834 , 0.99738264, 0.99854946],
       [0.99159753, 0.9990808 , 0.9985578 ],
       [0.9918705 , 0.9996991 , 0.9950943 ],
       [0.99979067, 0.99732506, 0.9962759 ],
       [0.9944825 , 0.98710966, 0.9969741 ],
       [0.9960071 , 0.9994142 , 0.9947804 ],
       [0.99560046, 0.9984194 , 0.9975488 ],
       [0.9936645 , 0.9871861 , 0.9955751 ],
       [0.9970095 , 0.9958494 , 0.9994563 ],
       [0.98042405, 0.9971843 , 0.9917098 ],
     

**8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`**

In [47]:
M = tf.random.Generator.from_seed(59)
M = M.normal(shape=(1, 224, 224, 3))
M

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.9465717 , -0.7108357 ,  1.2995545 ],
         [-0.61490655, -1.4713507 , -0.10086866],
         [ 0.9603878 , -1.6370124 ,  0.17664973],
         ...,
         [-0.38297576,  1.2623392 ,  0.8495842 ],
         [ 0.99230295,  0.24238716, -2.0003314 ],
         [-1.169094  ,  1.2556325 ,  2.3346927 ]],

        [[-1.0455614 ,  0.67605704, -1.2596191 ],
         [ 1.1185561 , -0.66418576,  1.6453402 ],
         [ 0.5407426 ,  0.8166653 , -0.30014586],
         ...,
         [-1.3063022 , -0.47231916, -2.3699439 ],
         [-0.75702274, -0.31284124,  0.3135117 ],
         [ 2.0003483 ,  1.5483569 ,  1.8376813 ]],

        [[-0.6554853 ,  0.14227922, -0.3523925 ],
         [-0.45585772, -1.9832319 , -0.36931053],
         [-0.01361591,  0.8295046 ,  0.7506118 ],
         ...,
         [ 0.37591147, -0.46919104,  0.9620095 ],
         [ 0.8616926 , -0.8323272 , -2.2296379 ],
         [ 0.77307785,  0.5656783 ,  0.7112601

In [48]:
tf.squeeze(M)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.9465717 , -0.7108357 ,  1.2995545 ],
        [-0.61490655, -1.4713507 , -0.10086866],
        [ 0.9603878 , -1.6370124 ,  0.17664973],
        ...,
        [-0.38297576,  1.2623392 ,  0.8495842 ],
        [ 0.99230295,  0.24238716, -2.0003314 ],
        [-1.169094  ,  1.2556325 ,  2.3346927 ]],

       [[-1.0455614 ,  0.67605704, -1.2596191 ],
        [ 1.1185561 , -0.66418576,  1.6453402 ],
        [ 0.5407426 ,  0.8166653 , -0.30014586],
        ...,
        [-1.3063022 , -0.47231916, -2.3699439 ],
        [-0.75702274, -0.31284124,  0.3135117 ],
        [ 2.0003483 ,  1.5483569 ,  1.8376813 ]],

       [[-0.6554853 ,  0.14227922, -0.3523925 ],
        [-0.45585772, -1.9832319 , -0.36931053],
        [-0.01361591,  0.8295046 ,  0.7506118 ],
        ...,
        [ 0.37591147, -0.46919104,  0.9620095 ],
        [ 0.8616926 , -0.8323272 , -2.2296379 ],
        [ 0.77307785,  0.5656783 ,  0.7112601 ]],

       ...,

     

**9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has maximum value**

In [53]:
N = tf.range(10)
O = tf.random.shuffle(N)
O

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 7, 5, 2, 3, 9, 0, 8, 4, 1], dtype=int32)>

In [55]:
tf.argmax(O).numpy(), tf.argmin(O).numpy()

(5, 6)

**10. One-hot encode the tensor you created in 9**

In [58]:
P = tf.one_hot(O, depth=O.shape[0])
P

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>